build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
images:
- dockerfile_path: Dockerfile
  to: troubleshooting-panel-console-plugin
- dockerfile_path: Dockerfile.test
  to: troubleshooting-panel-console-plugin-test
promotion:
  to:
  - excluded_images:
    - monitoring-plugin-test
    name: "4.16"
    namespace: ocp
releases:
  initial:
    integration:
      name: "4.16"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.16"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: lint
  commands: yarn lint
  container:
    from: troubleshooting-panel-console-plugin-test
zz_generated_metadata:
  branch: main
  org: openshift
  repo: troubleshooting-panel-console-plugin
